nginx:
    image: ihciah/google-mirror:latest
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./nginx/certs:/etc/nginx/certs:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
        - "80:80"
        - "443:443"

